language: java
dist: trusty

before_install:
  - rm -rf $HOME/.m2/repository/io/vlingo
  - cp travis_settings.xml $HOME/.m2/settings.xml

script:
  - mvn install

before_cache:
  - rm -rf $HOME/.m2/repository/io/vlingo
cache:
  directories:
    - $HOME/.m2/repository

deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: d-led
  on:
    branch: master
  key:
    secure: iiqYOtYP1+0m7MFtHw/GBWKDnavEt1100Lp0/PCAzMSMSQdUh2H1DPvhTRgS8pWk7FY1xW7FbE7StkCPFvQ/zSE8aMHmOGDgeaVskzMikARsePJeZmTpXOITAmBejYojw5Cw40v1bmHw+rjvvdU6DuNhC37ufMA3gYuKmFSnp0yuZHOM/FHAbSwEPJ/ctILxqAEMR8cvyILQiBt411vLMWj/LJdQy+G06MZJ9FsngFOTx99C2FrbjdtJB933p4e4Y8kA7flNvFglknsRArETqghAePH8vYEppxsIoAXsRIIVVTM0n+bVQey5ZIUiIdzjhwiyuj40i3XzQqP0qDHB4peyikXoyMTL+TWLlUei2W7F1tsy0CaRqyRBNH/WkGeoiG2GkzqeQ0h1fghXP4+exqFtH0DqXr+OohaE0EzJYRlmDEEeLjZrG9Y70WuQbRPX7qYxUTR0BHlCaDWnNDjbb6PHCgQBI6FRFcseebR9u0u2CBKrKL18k+rJAIY50qMZof4tCyk7fMmtY/YPg4Lw55xcIDQ/E1T+FjJwGTgEKEVvCd1wuYxCd10vB/D7S2XtDEeRtsnTArN8NeT4jFNvRZvWipiuJBbqvnhdlz5hthXY5v5XziWqDab1CEixYS922X3thIWjvd7zYWsoh0KUsBelY8lAGHH9H6MZrcRr0+w=
  passphrase:
    secure: WrPibdk1YDTMYfF6fH/2LB5sRKcFFm++lVfT0TrGOn2NmWDDu5Lu9gQDaMxogXhywfQPhieMeZXaOl5C/R4y62VpYzQC6Mqv6Tnm1QwK1mf8tcgjreqnhEeXgsvYnJjoyHO/r/2+1NtTiu88kq9oTSfK84rC2RmPZAWMVXoIrBX5vprO0lxgGvOOvxYZDLdpEzBMvCmfY8OeK81JIEnlwY9SSGGsTV9Zi1TvWa/gOurdGdB8OjzxN+wt8JZMSVG6jeMrxdAEELQKXBhDrEiuNzl+2AMyrsxlfG9kCnlU+hCIpOOyd76PyjpG63u0l/1zD6SnrO+Z4QgXaK1NHJxr2EU/6Gmfmlca9aOAfxHIleUNZbJXiWOGa8Z52IbGpJzCs+lwC8Rrs+VTGkrelr2DPiyQ7ZYhzxW2ImfG8nHS6mE6aMOksgzyKshgysylpzVpV8TvqcAGgRxeueFCwT6EtyxH51R5rk1pQYa+R/6v1HZU8D+guo0DnsNC8JKweysV5gYIQHSwDY6Yb7bCBCnInEdMEH/F7qGJf0KGugX8SKZqIYDvluLUlWKcDuDYJ15j5PHwOhS7SLWWZef+im/bqB4i+Mk+mX3Uvxr60r/ffq30I5oOWvC+EhMGTNxsbxJRPkYDOdseAUcXyBxERQhjb/+qjz8ZDwChd4iUOGwb5uI=
notifications:
  slack:
    secure: XknQKK9CcPTo5hIkrz4xu2bZXvbWuyVEKnFw1rOI+Mz7b54AtvB77vhXniLYtVsQxhF/+CIFu8wyIko7yNMBA4CiSTVyfiZqHra3tKEgQyx4V81Lj310w49BWWBkK3I7tx7s4ZirmmvLbLXPs3xXQoPy8J9bixvQpfP9SPC3xW0gG1lNvZpkPGtqS8pWl1Jr6ddJrdhbto19bKP2AZnK8W9lw++8rNyBvjItUIBSteYlSlz9IIzRkXrFpETtZqNG9jCKtj7sthWA5eeHUeyWJa6ZBY/fTpFz5t0/Mn9z0/Kmje3zLLXbsS8UIcTTUaBKluBQ2Wvg+zad6km3aKam4FMnyvvNiZRQEA33TDIzMhAsRGCyXcHJeeS+8eYuY/iZZBbUe+Rr6z/f0nXDk5if9KUSbifFF1zCEzntFoW4p9QyEwqinEw7qEKaTz49txAss4Zimd3ns1IES5btmL7GrDGzmwQYpjwu/E6TBLUF5XfBsECJPDXaMbOJiNTI4WArsHL3X12luvxZjwaOvSu9CyiDnMWNUYShaHhSUlhVeA39Bjj1Wtj1ZjyNEspCBDI3RzRFsq+3eUCOpp9/hAJvOttcvxDfMPeZFLn/Rf6doFTh+bhZ5dJJ6u0CLyyPqhv7H6km0Sa5HcsKj7FXHDP27UCkKshJgXNmc9+9LLMEWEs=
